<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Payplug\Payments\Block\Formjs;

/** @var Escaper $escaper */
/** @var Formjs $block */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
?>

<script>
    window.PAYPLUG_DOMAIN = '<?= $escaper->escapeJs($block->getPayplugSecureUrl()) ?>';

    (() => {
        window.addEventListener('checkout:payment:method-activate', (event) => {
            window.dispatchEvent(new Event('clear-messages'));

            if (event.detail.method !== 'payplug_payments_apple_pay') {
                const btnPlaceOrder = document.querySelector('.btn-place-order');
                btnPlaceOrder.disabled = false;
            }
        });
    })();
</script>

<?php $hyvaCsp->registerInlineScript() ?>
