<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 * @var HyvaCsp $hyvaCsp
 * @var ViewModelRegistry $viewModels
 */

if ($block->quoteHasBundleProductItem()) {
    return;
}
?>

<?= $block->getChildHtml('button.apple.pay.script') ?>

<script>
    'use strict';

    function initApplePayCart () {
        return {
            workflowType: 'shopping-cart'
        }
    }
</script>

<?php $hyvaCsp->registerInlineScript() ?>

<div x-data="cartButtonApplePay"
     class="pp-apple-pay-button mt-4 mb-8"
     @private-content-loaded.window="cartButtonApplePayPrivateContentLoadedWindow1">
    <apple-pay-button
        buttonstyle="black"
        type="pay"
        @click="cartButtonApplePayClick"
        x-show="isVisible"
        x-cloak>
    </apple-pay-button>
</div>

<script>
    function cartButtonApplePay() {
        return Object.assign(
            {...initApplePay(), ...initApplePayCart()},
            {
                ['cartButtonApplePayClick'](event) {return this.initApplePaySession()},
                ['cartButtonApplePayPrivateContentLoadedWindow1'](event) {
                    return this.onPrivateContentLoaded(this.$event.detail.data)
                },
            }
        )
    }
    window.addEventListener('alpine:init', () => {
        Alpine.data('cartButtonApplePay', cartButtonApplePay)
    }, {once: true});
</script>

<?php $hyvaCsp->registerInlineScript() ?>
