<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
?>

<script>
    (() => {
        hyvaCheckout.api.after(() => {
            let btnPlaceOrder;

            hyvaCheckout.payment.registerMethod({
                code: 'payplug_payments_apple_pay',
                method: {
                    initialize: async function () {
                        this.applePayPaymentData = document.getElementById('pp-apple-pay-payment').dataset;

                        this.loadApplePayApi().then(async () => {
                            if (this.checkLoadedAP()) {
                                document.querySelector('apple-pay-button').addEventListener('click', () => {
                                    hyvaCheckout.main.getWireComponent().placeOrder();
                                    this.initApplePay();
                                });

                                btnPlaceOrder = document.querySelector('.btn-place-order');

                                if (btnPlaceOrder) {
                                    btnPlaceOrder.disabled = true;
                                }
                            }
                        });
                    },
                    initApplePay: function() {
                        if (!ApplePaySession) {
                            return;
                        }

                        const versionNumber = this.getApplePayVersion();
                        const sessionRequest = this.getApplePaySessionRequest();
                        const session = new ApplePaySession(versionNumber, sessionRequest);

                        hyvaCheckout.evaluation.registerExecutable('make:pay-plug:payment', () => {
                            magewire.plugins.loader.start();
                            return new Promise((resolve) => {
                                session.onvalidatemerchant = async () => {
                                    fetch('<?= $escaper->escapeUrl($block->getUrl("payplug_payments/applepay/getTransactionData")); ?>').then(async response => {
                                        let res = await response.json();
                                        if (res.error === true) {
                                            window.location.replace('<?= $escaper->escapeUrl($block->getUrl('payplug_payments/payment/cancel')); ?>');
                                            reject();
                                        } else {
                                            session.completeMerchantValidation(res.merchand_data);
                                        }
                                    });
                                };

                                session.onpaymentauthorized = event => {
                                    const body = new URLSearchParams({
                                        form_key: hyva.getFormKey(),
                                        token: JSON.stringify(event.payment.token)
                                    });
                                    fetch('<?= $escaper->escapeUrl($block->getUrl("hyva_checkout_payplug/applepay/updateTransaction")); ?>', {
                                        method: 'POST',
                                        credentials: "include",
                                        body,
                                        headers: {
                                            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
                                        }
                                    }).then(async response => {
                                        let res = await response.json();
                                        let applePaySessionStatus = ApplePaySession.STATUS_SUCCESS;
                                        if (res.error === true) {
                                            applePaySessionStatus = ApplePaySession.STATUS_FAILURE;
                                        }
                                        session.completePayment({
                                            "status": applePaySessionStatus
                                        });
                                        if (res.error === true) {
                                            window.location.replace('<?= $escaper->escapeUrl($block->getUrl('payplug_payments/payment/cancel')); ?>');
                                            reject();
                                        } else {
                                            window.location.replace('<?= $escaper->escapeUrl($block->getUrl('payplug_payments/payment/paymentReturn')); ?>');
                                            resolve();
                                        }
                                    });
                                };

                                session.oncancel = event => {
                                    window.location.replace('<?= $escaper->escapeUrl($block->getUrl('payplug_payments/payment/cancel')); ?>');
                                };

                                session.begin();
                            });
                        });
                    },
                    getApplePayVersion: function() {
                        return ApplePaySession.supportsVersion(14) ? 14 : 3;
                    },
                    getApplePaySessionRequest: function() {
                        const { 
                            domain, 
                            merchantName, 
                            shippingCountryId, 
                            total 
                        } = this.applePayPaymentData;

                        return {
                            "countryCode": shippingCountryId,
                            "currencyCode": 'EUR',
                            "merchantCapabilities": ["supports3DS"],
                            "supportedNetworks": ["visa", "masterCard"],
                            "total": {
                                "label": merchantName,
                                "type": "final",
                                "amount": total
                            },
                            'applicationData': btoa(JSON.stringify({
                                'apple_pay_domain': domain
                            }))
                        };
                    },
                    loadApplePayApi: function() {
                        return new Promise(resolve => {
                            const script = document.createElement('script');
                            script.type = 'text/javascript';
                            script.src =  '<?= $escaper->escapeJs('https://applepay.cdn-apple.com/jsapi/1.latest/apple-pay-sdk.js') ?>';
                            script.async = true;
                            script.onload = resolve;
                            document.head.appendChild(script);
                        });
                    },
                    checkLoadedAP: function() {
                        return document.body.contains(document.querySelector('apple-pay-button'));
                    },
                    uninitialize: async function () {
                        btnPlaceOrder.disabled = false;
                    }
                }
            });
        });
    })();
</script>
<?php $hyvaCsp->registerInlineScript() ?>
