<?php
declare(strict_types=1);


use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;

/** @var Hyva\CheckoutPayplug\Block\Checkout\Payment\Method\Standard $block */
/** @var ViewModelRegistry $viewModels */
/** @var Hyva\CheckoutPayplug\Model\Magewire\Payment\Method\Standard $magewire */
/** @var \Magento\Framework\Escaper $escaper */

$icons = $viewModels->require(PayplugIcons::class);

$config = $magewire->getConfig();
$paymentConfig = $config['payment'];


$t = function (string $text) use ($escaper) {
  return $escaper->escapeHtml(__($text));
};

$tJs = function (string $text) use ($escaper) {
  return $escaper->escapeJs(__($text));
};

$integrated = false;
if(isset($paymentConfig["payplug_payments_standard"])){
  $integrated = $paymentConfig["payplug_payments_standard"]["is_integrated"];
}

?>
<?php
if($integrated){
?>
<div wire:id="checkout.payment.method.payplug_payments_standard" xmlns:wire="http://www.w3.org/1999/xhtml">

  <form id="payplug-payment-form" class="payplug IntegratedPayment -loaded">
    <div id="cardholder-input-container" class="payplug IntegratedPayment_container -cardHolder cardHolder-input-container" data-e2e-name="cardHolder">
    </div>
    <div class="error-container cardholder-input-container">
      <div class="invalid-field"><span><?= $t('Invalid Name and/or Last Name.' ); ?></span></div>
      <div class="empty-field"><span><?= $t('Mandatory field.' ); ?></span></div>
    </div>

    <div class="payplug IntegratedPayment_container -scheme">
    <div class="card-title"> <?= $t('Your card' ); ?> </div>
    <div class="payplug IntegratedPayment_schemes">
      <label class="payplug IntegratedPayment_scheme -visa"><input type="radio" name="schemeOptions" value="visa"/><span></span></label>
      <label class="payplug IntegratedPayment_scheme -mastercard"><input type="radio" name="schemeOptions" value="mastercard" /><span></span></label>
      <label class="payplug IntegratedPayment_scheme -cb"><input type="radio" name="schemeOptions" value="cb" /><span></span></label>
    </div>
    </div>
    <div id="pan-input-container" class="payplug IntegratedPayment_container -pan pan-input-container" data-e2e-name="pan"></div>
    <div class="error-container pan-input-container">
      <div class="invalid-field"><span><?= $t('Invalid card number.' ); ?></span></div>
      <div class="empty-field"><span><?= $t('Mandatory field.' ); ?></span></div>
    </div>
    <div class="exp-cvv-container">
      <div>
        <div id="exp-input-container" class="payplug IntegratedPayment_container -exp exp-input-container" data-e2e-name="expiration"></div>
        <div class="error-container exp-input-container">
          <div class="invalid-field"><span><?= $t('Invalid expiration date.' ); ?></span></div>
          <div class="empty-field"><span><?= $t('Mandatory field.' ); ?></span></div>
        </div>
      </div>

      <div>
        <div id="cvv-input-container" class="payplug IntegratedPayment_container -cvv cvv-input-container" data-e2e-name="cvv"></div>
        <div class="error-container cvv-input-container">
          <div class="invalid-field"><span><?= $t('Invalid CVV.' ); ?></span></div>
          <div class="empty-field"><span><?= $t('Mandatory field.' ); ?></span></div>
        </div>
      </div>

    </div>
    <div class="transaction-secured">
      <img src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>"" alt="">
      <span><?= $t('Transaction secured by' ); ?></span>
      <img class="payplug-logo" src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('payplug')); ?>"" alt="">
    </div>

    <div class="policy">
      <a href="<?= $t('payplug-integrated-privacy-policy-link' ); ?>" title=" <?= $t('Privacy Policy' ); ?>" target="_blank">
        <?= $t('Privacy Policy' ); ?>
      </a>
    </div>

  </form>

</div>
<style>

  .error-container.cardholder-input-container,
  .error-container.pan-input-container,
  .error-container.exp-input-container,
  .error-container .cvv-input-container{
    font-size: 14px;
  }

  #payplug-payment-form.IntegratedPayment .exp-cvv-container {
    display: flex;
    gap: 10px;
    justify-content: space-between;
    margin-top: 10px;
  }

  #payplug-payment-form.IntegratedPayment .transaction-secured{
    color: #212225;
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 10px;
    width: 100%;
  }

  #payplug-payment-form.IntegratedPayment .transaction-secured img{
    height: 16px;
  }

  #payplug-payment-form.IntegratedPayment .transaction-secured img.payplug-logo{
    min-width: 90px;
  }

  #payplug-payment-form.IntegratedPayment .transaction-secured,
  #payplug-payment-form.IntegratedPayment .policy{
    font-size: 14px;
    line-height: 21px;
    width: 100%;
    text-align: center;
    font-size: 14px;
    line-height: 21px;
  }

  #payplug-payment-form.IntegratedPayment .policy a{
    display: block;
    color: #909192;
    text-decoration: underline;
  }

  #payplug-payment-form.IntegratedPayment .invalid-field,
  #payplug-payment-form.IntegratedPayment .empty-field {
    color: #E91932;
    display: none;
  }

    .IntegratedPayment {
        width: 300px;
        display: block;
        justify-content: space-between;
        margin-bottom: 0px;
    }
    .IntegratedPayment.-loaded {
        margin-top: 20px;
    }
    .IntegratedPayment_select {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 0 8px;
        margin: 0 0 10px;
        height: 36px;
        width: 100%;
    }
    .IntegratedPayment_container {
        display: flex;
        padding: 0;
        margin: 0 0 10px;
        width: 100%;
        position: relative;
    }
    .IntegratedPayment_container.-cardHolder, .IntegratedPayment_container.-pan, .IntegratedPayment_container.-exp, .IntegratedPayment_container.-cvv {
        height: 40px;
        line-height: 40px;
        border-radius: 2px;
        padding: 0 16px 0 50px;
        cursor: text;
        border: solid 1px #d5d6d8
    }
    .IntegratedPayment_container.-cardHolder:before, .IntegratedPayment_container.-pan:before, .IntegratedPayment_container.-exp:before, .IntegratedPayment_container.-cvv:before {
        content: "";
        position: absolute;
        top: 20%;
        left: 16px;
        width: 24px;
        height: 24px;
        background: #95999e 50% no-repeat;
        background-size: 100% auto;
    }

    .payplugIntegratedPayment_schemes label {
        display: table-cell;
    }

    .IntegratedPayment_container.-cardHolder.-focus, .IntegratedPayment_container.-pan.-focus, .IntegratedPayment_container.-exp.-focus, .IntegratedPayment_container.-cvv.-focus {
        border-color: #2b343d;
    }
    .IntegratedPayment_container.-cardHolder.-invalid, .IntegratedPayment_container.-pan.-invalid, .IntegratedPayment_container.-exp.-invalid, .IntegratedPayment_container.-cvv.-invalid {
        border-color: #E91932;
    }
    .IntegratedPayment_container.-cardHolder:before {
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
    }
    .IntegratedPayment_container.-pan:before {
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
    }
    .IntegratedPayment_container.-exp, .IntegratedPayment_container.-cvv {
        max-width: calc(140px);
        display: block;
    }
    .IntegratedPayment_container.-cvv:before {
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
    }
    .IntegratedPayment_container.-exp:before {
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
    }
    .IntegratedPayment_container.-scheme {
        justify-content: space-between;
        align-items: center;
        font-size: 14px;
        font-weight: 700;
        text-transform: uppercase;
        height: 22px;
        margin: 10px 0;
    }
    .IntegratedPayment_container.-saveCard {
        display: flex;
        height: auto;
        align-items: center;
        padding: 10px 0 0;
    }
    .IntegratedPayment_container.-saveCard label {
        margin: 0;
        cursor: pointer;
        font-size: 12px;
        color: #918f8f;
    }

    .IntegratedPayment_container.-saveCard label span {
        border: 1px solid #d5d6d8;
        border-radius: 2px;
        cursor: pointer;
        display: inline-block;
        height: 16px;
        margin: 0 10px -3px 0;
        position: relative;
        -webkit-transition: border .4s;
        -moz-transition: border .4s;
        -ms-transition: border .4s;
        -o-transition: border .4s;
        transition: border .4s;
        width: 16px;
    }
    .IntegratedPayment_container.-saveCard label span:before {
        border: 2.5px solid #2b343d;
        border-radius: 1px;
        border-right: none;
        border-top: none;
        content: "";
        display: block;
        height: 3px;
        left: 50%;
        opacity: 0;
        position: absolute;
        top: 50%;
        -webkit-transform: translate(-50%,-55%) rotate(-48deg);
        -moz-transform: translate(-50%,-55%) rotate(-48deg);
        -ms-transform: translate(-50%,-55%) rotate(-48deg);
        -o-transform: translate(-50%,-55%) rotate(-48deg);
        transform: translate(-50%,-55%) rotate(-48deg);
        -webkit-transition: opacity .4s;
        -moz-transition: opacity .4s;
        -ms-transition: opacity .4s;
        -o-transition: opacity .4s;
        transition: opacity .4s;
        width: 9px;
    }
    .IntegratedPayment_container.-saveCard label input {
        display: none;
    }
    .IntegratedPayment_container.-saveCard label:hover span {
        border-color: #2b343d;
        transition: 0.1s;
    }
    .IntegratedPayment_container.-saveCard label:hover {
        color: #2b343d;
        transition: 0.1s;
    }
    .IntegratedPayment_container.-saveCard.-checked label span:before {
        opacity: 1;
    }
    .IntegratedPayment_container.-deferred {
        margin: 10px 0;
        background: #E9EAEB;
        padding: 4px 15px;
        font-size: 12px;
        color: #2B343D;
        display: block;
        text-align: center;
    }
    .IntegratedPayment_container.-transaction{
        display: inline-block;
        margin-top: 10px;
    }
    .IntegratedPayment_container img.lock-icon{
        width: 18px;
        float: left !important;
    }
    .IntegratedPayment_container .transaction-label{
        font-size: 12px;
        margin-left: 5px;
        vertical-align: super;
    }
    .IntegratedPayment_container .payplug-logo{
        width: 80px;
        height: auto;
        display: inline-block;
        float: inherit !important;
        margin-left: 6px;
        vertical-align: text-top;
    }
    .IntegratedPayment_container.-privacy-policy{
        display: inline-block;
        text-align: center;
    }
    .IntegratedPayment_container.-privacy-policy a{
        color: #918f8f;
        font-size: 14px;
    }
    .IntegratedPayment_error {
        color: #E91932;
        font-size: 12px;
        margin: -10px 0 10px;
        width: 100%;
        line-height: 18px;
        padding-left: 4px;
    }
    .IntegratedPayment_error.-cardHolder {
        margin: -10px 0 0;
    }
    .IntegratedPayment_error.-exp, .IntegratedPayment_error.-cvv {
        width: 100%;
        max-width: calc(49%);
    }
    .IntegratedPayment_error.-cvv {
        justify-self: flex-end;
        margin: -10px 0 10px auto;
    }
    .-hide {
        display: none;
    }
    .IntegratedPayment_error.-payment, .IntegratedPayment_error.-fields, .IntegratedPayment_error.-api {
        display: none;
        background: rgba(233,25,50,0.08);
        color: #e91932;
        text-align: center;
        width: 100%;
        line-height: 18px;
        align-items: center;
        justify-content: center;
        margin: 10px 0 0;
        padding: 4px 0;
    }
    .IntegratedPayment_error.-payment.-show, .IntegratedPayment_error.-fields.-show, .IntegratedPayment_error.-api.-show {
        display: flex;
    }
    .IntegratedPayment_scheme {
        margin: 0;
    }
    .IntegratedPayment_schemes {
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-wrap: wrap;
        width: 115px;
    }
    .IntegratedPayment_scheme span {
        cursor: pointer;
        display: block;
        width: 33px;
        height: 22px;
        background: 50% no-repeat;
        background-size: 100% auto;
    }
    .IntegratedPayment_scheme span:before {
        display: block;
        width: 100%;
        height: 100%;
        content: "";
        background: 50% no-repeat;
        background-size: 100% auto;
        opacity: 0;
    }
    .IntegratedPayment_scheme input {
        display: none;
    }
    .IntegratedPayment_scheme input:checked + span:before {
        opacity: 1;
    }
    .IntegratedPayment_scheme.-visa span {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('visa-dark')); ?>');
    }
    .IntegratedPayment_scheme.-visa span:before {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('visa')); ?>');
    }
    .IntegratedPayment_scheme.-mastercard span {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('mastercard-dark')); ?>');
    }
    .IntegratedPayment_scheme.-mastercard span:before {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('mastercard')); ?>');
    }
    .IntegratedPayment_scheme.-cb span {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('cb-dark')); ?>');
    }
    .IntegratedPayment_scheme.-cb span:before {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('cb')); ?>');
    }
    .IntegratedPayment .ipOverlay {
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        position: fixed;
        background-color: rgba(25,25,25,0.5);
        z-index: 100;
    }
    .IntegratedPayment .ipOverlay_inner {
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        position: absolute;
    }
    .IntegratedPayment .ipOverlay_content {
        left: 50%;
        position: absolute;
        top: 50%;
        transform: translate(-50%,-50%);
    }
    .IntegratedPayment .ipOverlay_spinner {
        width: 75px;
        height: 75px;
        display: inline-block;
        border-width: 2px;
        border-color: rgba(255,255,255,0.05);
        border-top-color: #fff;
        animation: spin 1s infinite linear;
        border-radius: 100%;
        border-style: solid;
        position: fixed;
        top: 50%;
        left: 50%;
    }
    @keyframes spin {
    .IntegratedPayment .ipOverlay 0% {
        transform: rotate(0deg);
    }
    .IntegratedPayment .ipOverlay 100% {
        transform: rotate(360deg);
    }
    }


</style>

<script>
  (() => {

    window.PAYPLUG_DOMAIN = "https://secure-qa.payplug.com";
    // Create an instance of IntegratedPayment
    var IntegratedPayment = {
      props: {
        cartId: null,
        paymentId: null,
        paymentOptionId: null,
        form: {},
        checkoutForm: null,
        api: null,
        integratedPayment: null,
        token: null,
        notValid: true,
        fieldsValid: {
          cardHolder: false,
          pan: false,
          cvv: false,
          exp: false,
        },
        fieldsEmpty: {
          cardHolder: true,
          pan: true,
          cvv: true,
          exp: true,
        },
        inputStyle: {
          default: {
            color: '#2B343D',
            fontFamily: 'Poppins, sans-serif',
            fontSize: '14px',
            textAlign: 'left',
            '::placeholder': {
              color: '#969a9f',
            },
            ':focus': {
              color: '#2B343D',
            }
          },
          invalid: {
            color: '#E91932'
          }
        },
        save_card: false,
        scheme: null,
        query: null,
        submit: null,
        order_review: false,
        return_url: null
      },
      init: function () {

        //TODO:: the is_sandbox needs to be dinamic
        IntegratedPayment.props.api = new Payplug.IntegratedPayment(<?= $paymentConfig['payplug_payments_standard']['is_sandbox']; ?>);
        IntegratedPayment.props.api.setDisplayMode3ds(Payplug.DisplayMode3ds.LIGHTBOX);

        IntegratedPayment.props.form = {};
        //draw Name
        IntegratedPayment.props.form.cardHolder = {element: IntegratedPayment.props.api.cardHolder(document.querySelector('#cardholder-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'Name'})};

        //draw card
        IntegratedPayment.props.form.pan = {element:IntegratedPayment.props.api.cardNumber(document.querySelector('#pan-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'Card Number'})};

        //draw cvv
        IntegratedPayment.props.form.cvv = {element:IntegratedPayment.props.api.cvv(document.querySelector('#cvv-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'CVV'})};

        //draw date
        IntegratedPayment.props.form.exp = {element:IntegratedPayment.props.api.expiration(document.querySelector('#exp-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'Exp Date'})};

        //draw schemes
        IntegratedPayment.props.scheme = IntegratedPayment.props.api.getSupportedSchemes();

      },
    };


    window.addEventListener('checkout:payment:method-activate', (event) => {
      if (event.detail.method == "payplug_payments_standard") {
        hyvaCheckout.payment.activate('payplug_payments_standard', {

          initialize() {
            this.loadHostedLib().then(()=>{
              if(!this.checkLoaded()){
                IntegratedPayment.init();
              }
            });
          },
          loadHostedLib(){
            return new Promise((resolve, reject) => {

              if (!document.getElementById('payplug_hosted_lib')) {
                const script = document.createElement('script');
                script.src = 'https://cdn-qa.payplug.com/js/integrated-payment/v1@1/index.js';
                script.setAttribute('id', 'payplug_hosted_lib');
                document.head.append(script);
              }

              //if it's not loaded yet let's wait 100ms to load it
              let count = 0;
              const interval = setInterval(() => {
                count++;
                if (typeof Payplug !== 'undefined') {
                  clearInterval(interval);
                  resolve();
                  return;
                }

                if (count > 100) {
                  reject();
                  clearInterval(interval);
                  throw new Error('Unable to load Payplug');
                }
              }, 100);
            });
          },
          checkLoaded: function(){
            return document.body.contains(document.getElementById('cardholder'));
          },
          /**
           * Whenever the customer clicks "next" or "place order", depending on the checkout settings, the payment
           * is validated. When this is successful, Stripe returns a payment method id,
           * which is then set on the quote.
           *
           * @returns {Promise<unknown>}
           */
          validate() {

            let self = this;

            return new Promise(async (resolve, reject) => {
                IntegratedPayment.props.api.setDisplayMode3ds(Payplug.DisplayMode3ds.LIGHTBOX);
              console.log(IntegratedPayment.props.api.validateForm());
              IntegratedPayment.props.api.onValidateForm(({isFormValid}) => {
                  magewire.plugins.loader.start();
                console.log("onValidateForm");
                if (isFormValid) {
                  console.log("all good :thumbs_up");

                    try{

                      fetch('<?php echo $block->getUrl("hyva_checkout_payplug/payment/standard");?>?should_redirect=0&integrated=1').then(response => {
                        let res = response.clone().json();

                        res.then( result => {

                          if(typeof result.error !== 'undefined' && result.error){
                            console.log(response.message);
                            window.location.replace(response.url);
                            reject();
                            throw new Error(`Error! status: ${response.message}`);

                          }else{
                            console.log(result.payment_id)

                            if (typeof result.payment_id !== undefined && result.payment_id) {

                              IntegratedPayment.props.api.pay(result.payment_id, 0, {save_card: 0});
                              IntegratedPayment.props.api.onCompleted(function (event) {
                                window.location.replace('<?php echo $block->getBaseUrl();?>payplug_payments/payment/paymentReturn');
                             });

                            } else {
                              window.location.replace('<?php echo $block->getBaseUrl();?>payplug_payments/payment/cancel');
                              reject();

                            }
                          }






                        });
                      }).catch(err => {
                        reject();
                        console.log(err);
                      });

                    } catch (error){
                      reject()
                    }
                } else {
                  console.log(isFormValid + ": form not valid");
                    magewire.plugins.loader.stop();
                    return false;
                }
              });
            });

          },
        }, document.getElementById('payplug-payment-form'), 'payment');


      } else {
        var script = document.getElementById("payplug-js");
        if (script) {
          script.remove();
        }
        document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
        hyvaCheckout.payment.method = null;
      }

    }, {once: true});


    const cardholder = document.querySelector('#cardholder-input-container');
    const pan = document.querySelector('#pan-input-container');
    const exp = document.querySelector('#exp-input-container');
    const cvv = document.querySelector('#cvv-input-container');
    const options = { attributes: true }
    function callback(mutationList, observer) {
      mutationList.forEach(function(mutation) {
        if ( mutation.attributeName === 'class' ) {
          if(mutation.target.classList.contains("integrated_payment_error") ){
            mutation.target.style.border = "1px solid #FF0000";
            let id = mutation.target.id
            document.querySelector('.error-container.'+id+ ' .invalid-field').style.display = "block";
          }else{
            let id = mutation.target.id
            mutation.target.style.border = "1px solid #d5d6d8";
            document.querySelector('.error-container.'+id+ ' .invalid-field').style.display = "none";
          }
        }
      })
    }
    const observer = new MutationObserver(callback)
    observer.observe(cardholder, options)
    observer.observe(pan, options)
    observer.observe(exp, options)
    observer.observe(cvv, options)

  })();


</script>
    <?php
} else {
    ?>
    <div wire:id="checkout.payment.method.payplug_payments_standard"></div>
<?php
}
?>

