<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Payplug\Payments\Block\Oney\Simulation;
use Magento\Framework\Pricing\Helper\Data;
use Payplug\Payments\Gateway\Config\OneyWithoutFees;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Simulation $block */

$hasError = false;
$oneySimulation = $block->getOneySimulation();
$message = $oneySimulation->getMessage();

if (!$oneySimulation->getSuccess() || !empty($message)) {
    $hasError = true;
}

$isOneyWithoutFees = $oneySimulation->getMethod() === OneyWithoutFees::METHOD_CODE;
$pricingHelper = $this->helper(Data::class);

/** @var PayplugIcons $viewModels */
$icons = $viewModels->require(PayplugIcons::class);
?>
<div data-oney-container="payplug_payments_oney">
    <div class="oneyPayment oneyPayment-open"></div>
</div>

<div class="payment-method-content"></div>

<span class="oneyPopin <?php if ($hasError): ?>oneyPopin-error<?php endif; ?>"></span>

<style>
    <?php if($isOneyWithoutFees): ?>
        .oneyLogo-3x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('oney_without_fees/3x')); ?>');
        }
        .oneyLogo-4x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('oney_without_fees/4x')); ?>');
        }
    <?php else: ?>
        .oneyLogo-3x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('3x')); ?>');
        }
        .oneyLogo-4x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('4x')); ?>');
        }
    <?php endif; ?>
</style>

<script>
    const oneyContainer = document.querySelector('[data-oney-container="payplug_payments_oney"]');

    const getScheduleLabel = (days) => {
        const scheduleLabels = [
            {days: 30, label: "<?= $escaper->escapeJs(__('In 30 days')); ?>" },
            {days: 60, label: "<?= $escaper->escapeJs(__('In 60 days')); ?>" },
            {days: 90, label: "<?= $escaper->escapeJs(__('In 90 days')); ?>" },
        ];
        let label = null;
        scheduleLabels.forEach(function(item) {
            if (item.days === days) {
                label = item.label;

                return false;
            }
        });

        return label;
    }

    const selectOneyOption = (option) => {
        const oneyPayment = oneyContainer.querySelector('.oneyPayment');
        const oldSelected = oneyPayment.querySelector('.oneyOption-selected');
        const selectedOption = oneyContainer.querySelector('[data-type="'+ option +'"]');

        oldSelected && oldSelected.classList.remove('oneyOption-selected');
        selectedOption.classList.add('oneyOption-selected');

        updatePlaceOrderButtonLabel(option);
    }

    const updatePlaceOrderButtonLabel = (type) => {
        let label;

        if (type === null) {
            label = '<?= $escaper->escapeJs(__('Place Order')); ?>';
            hyva.replaceDomElement('.btn-primary[x-bind="buttonPlaceOrder()"]', `
                <button type="button"
                        class="btn btn-primary disabled:opacity-10 disabled:cursor-not-allowed bg-green-600 hover:bg-green-500"
                        x-spread="buttonPlaceOrder()"
                        x-bind="buttonPlaceOrder()"
                        data-step="{'place':true}">
                    Valider la commande
                </button>
            `);
        } else {
            label = getPaymentTypeLabel().replace('%1', type);
            hyva.replaceDomElement('.btn-primary[x-bind="buttonPlaceOrder()"]', `
                <button type="button"
                        class="btn btn-primary disabled:opacity-10 disabled:cursor-not-allowed bg-green-600 hover:bg-green-500"
                        x-spread="buttonPlaceOrder()"
                        x-bind="buttonPlaceOrder()"
                        data-step="{'place':true}">
                    ${label}
                </button>
            `);
        }
    }

    const getPaymentTypeLabel = () => {
        <?php $label = $isOneyWithoutFees ? 'Payment in %1 without fees' : 'Payment in %1'; ?>
        return '<?= $escaper->escapeJs(__($label)) ?>';
    }

    const buildOneyDetail = () => {
        var tmpDiv = document.createElement('div');
        var optionsWrapper = document.createElement('div');
        optionsWrapper.classList.add('oneyOption_wrapper');

        var label = getPaymentTypeLabel();

        <?php if ($hasError): ?>
            var error_is_displayed = document.querySelector("p.oneyPopin_error");

            if (typeof(error_is_displayed) === 'undefined' || error_is_displayed === null ){
                var error_message = document.createElement('p');
                error_message.classList.add('oneyPopin_error');
                error_message.innerHTML = "<?= $escaper->escapeJs($message); ?>";
                tmpDiv.appendChild(error_message);
            }
        <?php else : ?>
            <?php foreach ($oneySimulation->getOptions() as $option) : ?>
                var type = "<?= $escaper->escapeJs($option->getType()); ?>";
                var option = document.createElement('label');

                option.setAttribute('data-type', type);
                option.classList.add('oneyOption', 'oneyOption-' + type);

                <?php // Title ?>
                var title =  document.createElement('div');
                title.classList.add('oneyOption_title');

                var tmpSpan = document.createElement('span');
                tmpSpan.classList.add('oneyOption_logo', 'oneyLogo', 'oneyLogo-' + type);

                title.append(tmpSpan);
                title.innerHTML += label.replace('%1', type);

                option.append(title);

                <?php if ($option->getSchedules()) : ?>
                    var detail = document.createElement('div');
                    detail.classList.add('oneyOption_prices');

                    var list = document.createElement('ul');
                    list.classList.add('oneyOption_list');

                    var firstDeposit = document.createElement('li');
                    var totalAmoutSpan = document.createElement('span');

                    totalAmoutSpan.innerHTML += "<?= $escaper->escapeJs(__('Total order amount')); ?>";
                    firstDeposit.append(totalAmoutSpan);

                    var oneyOptionSpan = document.createElement('span');

                    oneyOptionSpan.classList.add('oneyOption_price');
                    oneyOptionSpan.innerHTML += "<?= $escaper->escapeJs($pricingHelper->currency($option->getFirstDeposit(), true, false)); ?>";
                    firstDeposit.append(oneyOptionSpan);
                    list.append(firstDeposit);

                    var daysForPayment = 30;

                    <?php foreach ($option->getSchedules() as $i => $schedule): ?>
                        var scheduleData = "<?= $escaper->escapeJs(__(sprintf('Installment %d:', $i + 1))); ?>";
                        var schedule = document.createElement('li');
                        var daysSpan = document.createElement('span');

                        daysSpan.innerHTML += getScheduleLabel(daysForPayment);
                        schedule.append(daysSpan);

                        var oneyOptionSpan2 = document.createElement('span');

                        oneyOptionSpan2.classList.add('oneyOption_price');
                        oneyOptionSpan2.innerHTML += "<?= $escaper->escapeJs($pricingHelper->currency($schedule->getAmount(), true, false)); ?>";
                        schedule.append(oneyOptionSpan2);
                        list.append(schedule);
                        daysForPayment += 30;
                    <?php endforeach; ?>

                    var totalAmout = document.createElement('li');
                    var totalCostSpanLabel = document.createElement('span');
                    totalCostSpanLabel.innerHTML += "<?= $escaper->escapeJs(__('Total cost')); ?>";

                    var totalCostSpan = document.createElement('span');
                    totalCostSpan.classList.add('oneyOption_price');
                    totalCostSpan.innerHTML += "<?= $escaper->escapeJs($pricingHelper->currency($option->getTotalAmount(), true, false)); ?>";

                    totalAmout.append(totalCostSpanLabel);
                    totalAmout.append(totalCostSpan);

                    list.append(totalAmout);
                    detail.append(list);
                    option.append(detail);
                <?php endif; ?>

                var radio = document.createElement('div');
                var radioDiv = document.createElement('div');
                var radioSpan = document.createElement('span');
                var radioInput = document.createElement('input');

                radioInput.setAttribute('type', 'radio');
                radioInput.setAttribute('name', 'oney_type');
                radioInput.value = type;

                radioSpan.append(radioInput);

                radio.classList.add('oneyOption_radio');
                radioDiv.classList.add('radio');
                radioDiv.append(radioSpan);
                radio.append(radioSpan);

                option.append(radio);
                optionsWrapper.append(option);
            <?php endforeach; ?>
        <?php endif; ?>

        tmpDiv.appendChild(optionsWrapper);
        oneyContainer.querySelector('.oneyPayment').appendChild(tmpDiv);
    }

    const oneyOptionsHandler = () => {
        const oneyOption3x = document.querySelector('.oneyOption-3x');
        const oneyOption4x = document.querySelector('.oneyOption-4x');

        if (oneyOption3x !== null){
            oneyOption3x.addEventListener('click', function () {
                const selected = oneyOption3x.querySelector('input[name="oney_type"]');
                selectOneyOption(selected.value);
            });
        }

        if (oneyOption4x !== null){
            oneyOption4x.addEventListener('click', function () {
                const selected = oneyOption4x.querySelector('input[name="oney_type"]');
                selectOneyOption(selected.value);
            });
        }
    }

    let oney_type = '';

    window.addEventListener('checkout:payment:method-activate', (event) => {
        if (event.detail.method == 'payplug_payments_oney' || event.detail.method == 'payplug_payments_oney_without_fees') {
            switch (event.detail.method){
                case 'payplug_payments_oney':
                    oney_type = 'payplug_payments_oney';
                    break;
                case 'payplug_payments_oney_without_fees':
                    oney_type = 'payplug_payments_oney_without_fees';
                    break;
                default:
                    oney_type = 'payplug_payments_oney';
        }

        hyvaCheckout.payment.activate(oney_type, {
            validate() {
                return new Promise(async (resolve, reject) => {
                    const selected = document.querySelector('input[name="oney_type"]:checked');
                    const option = await Magewire.find('checkout.payment.method.' + oney_type).call('setOneyType', selected.value);
                        resolve();
                    });
                }
            }, document.getElementById('payment-method-view-' + oney_type));

            const oney = document.querySelector('.oneyOption_wrapper');
            oney && document.querySelector('.oneyOption_wrapper').remove();

            buildOneyDetail();
            oneyOptionsHandler();
        }
    });
</script>
