<?php
declare(strict_types=1);


use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;

/** @var Hyva\CheckoutPayplug\Block\Checkout\Payment\Method\Integrated $block */
/** @var ViewModelRegistry $viewModels */


$icons = $viewModels->require(PayplugIcons::class);



?>




<div wire:id="checkout.payment.method.payplug_payments_standard" >
  <form id="payplug-payment-form" class="payplug IntegratedPayment -loaded">
      <div id="cardholder-input-container" class="payplug IntegratedPayment_container -cardHolder cardHolder-input-container" data-e2e-name="cardHolder"></div>
      <div class="payplug IntegratedPayment_container -scheme">
          <div></div>
          <div class="payplug IntegratedPayment_schemes">
              <label class="payplug IntegratedPayment_scheme -visa">
                  <input type="radio" name="schemeOptions" value="visa"/><span></span>
              </label>
              <label class="payplug IntegratedPayment_scheme -mastercard"><input type="radio" name="schemeOptions" value="mastercard" /><span></span></label>
              <label class="payplug IntegratedPayment_scheme -cb"><input type="radio" name="schemeOptions" value="cb" /><span></span></label>
          </div>
      </div>
      <div id="pan-input-container" class="payplug IntegratedPayment_container -pan pan-input-container" data-e2e-name="pan"></div>
      <div id="cvv-input-container" class="payplug IntegratedPayment_container -cvv cvv-input-container" data-e2e-name="cvv"></div>
      <div id="exp-input-container" class="payplug IntegratedPayment_container -exp exp-input-container" data-e2e-name="expiration"></div>
  </form>
</div>
<style>
    .IntegratedPayment {
        width: 100%;
        max-width: 400px;
        flex-wrap: wrap;
        justify-content: space-between;
        margin-bottom: 0px;
    }
    .IntegratedPayment.-loaded {
        display: flex;
        margin-top: 20px;
    }
    .IntegratedPayment_select {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 0 8px;
        margin: 0 0 10px;
        height: 36px;
        width: 100%;
    }
    .IntegratedPayment_container {
        display: flex;
        padding: 0;
        margin: 0 0 10px;
        width: 100%;
        position: relative;
    }
    .IntegratedPayment_container.-cardHolder, .IntegratedPayment_container.-pan, .IntegratedPayment_container.-exp, .IntegratedPayment_container.-cvv {
        height: 40px;
        line-height: 40px;
        border-radius: 2px;
        padding: 0 16px 0 50px;
        cursor: text;
        border: solid 1px #d5d6d8
    }
    .IntegratedPayment_container.-cardHolder:before, .IntegratedPayment_container.-pan:before, .IntegratedPayment_container.-exp:before, .IntegratedPayment_container.-cvv:before {
        content: "";
        position: absolute;
        top: 20%;
        left: 16px;
        width: 24px;
        height: 24px;
        background: #95999e 50% no-repeat;
        background-size: 100% auto;
    }

    .payplugIntegratedPayment_schemes label {
        display: table-cell;
    }

    .IntegratedPayment_container.-cardHolder.-focus, .IntegratedPayment_container.-pan.-focus, .IntegratedPayment_container.-exp.-focus, .IntegratedPayment_container.-cvv.-focus {
        border-color: #2b343d;
    }
    .IntegratedPayment_container.-cardHolder.-invalid, .IntegratedPayment_container.-pan.-invalid, .IntegratedPayment_container.-exp.-invalid, .IntegratedPayment_container.-cvv.-invalid {
        border-color: #E91932;
    }
    .IntegratedPayment_container.-cardHolder:before {

        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
    }
    .IntegratedPayment_container.-pan:before {
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
    }
    .IntegratedPayment_container.-exp, .IntegratedPayment_container.-cvv {
        max-width: calc(50% - 2px);
        display: inline-block;
    }
    .IntegratedPayment_container.-cvv:before {
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
    }
    .IntegratedPayment_container.-exp:before {
        mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
        -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
    }
    .IntegratedPayment_container.-scheme {
        justify-content: space-between;
        align-items: center;
        font-size: 14px;
        font-weight: 700;
        text-transform: uppercase;
        height: 22px;
        margin: 10px 0;
    }
    .IntegratedPayment_container.-saveCard {
        display: flex;
        height: auto;
        align-items: center;
        padding: 10px 0 0;
    }
    .IntegratedPayment_container.-saveCard label {
        margin: 0;
        cursor: pointer;
        font-size: 12px;
        color: #918f8f;
    }

    .IntegratedPayment_container.-saveCard label span {
        border: 1px solid #d5d6d8;
        border-radius: 2px;
        cursor: pointer;
        display: inline-block;
        height: 16px;
        margin: 0 10px -3px 0;
        position: relative;
        -webkit-transition: border .4s;
        -moz-transition: border .4s;
        -ms-transition: border .4s;
        -o-transition: border .4s;
        transition: border .4s;
        width: 16px;
    }
    .IntegratedPayment_container.-saveCard label span:before {
        border: 2.5px solid #2b343d;
        border-radius: 1px;
        border-right: none;
        border-top: none;
        content: "";
        display: block;
        height: 3px;
        left: 50%;
        opacity: 0;
        position: absolute;
        top: 50%;
        -webkit-transform: translate(-50%,-55%) rotate(-48deg);
        -moz-transform: translate(-50%,-55%) rotate(-48deg);
        -ms-transform: translate(-50%,-55%) rotate(-48deg);
        -o-transform: translate(-50%,-55%) rotate(-48deg);
        transform: translate(-50%,-55%) rotate(-48deg);
        -webkit-transition: opacity .4s;
        -moz-transition: opacity .4s;
        -ms-transition: opacity .4s;
        -o-transition: opacity .4s;
        transition: opacity .4s;
        width: 9px;
    }
    .IntegratedPayment_container.-saveCard label input {
        display: none;
    }
    .IntegratedPayment_container.-saveCard label:hover span {
        border-color: #2b343d;
        transition: 0.1s;
    }
    .IntegratedPayment_container.-saveCard label:hover {
        color: #2b343d;
        transition: 0.1s;
    }
    .IntegratedPayment_container.-saveCard.-checked label span:before {
        opacity: 1;
    }
    .IntegratedPayment_container.-deferred {
        margin: 10px 0;
        background: #E9EAEB;
        padding: 4px 15px;
        font-size: 12px;
        color: #2B343D;
        display: block;
        text-align: center;
    }
    .IntegratedPayment_container.-transaction{
        display: inline-block;
        margin-top: 10px;
    }
    .IntegratedPayment_container img.lock-icon{
        width: 18px;
        float: left !important;
    }
    .IntegratedPayment_container .transaction-label{
        font-size: 12px;
        margin-left: 5px;
        vertical-align: super;
    }
    .IntegratedPayment_container .payplug-logo{
        width: 80px;
        height: auto;
        display: inline-block;
        float: inherit !important;
        margin-left: 6px;
        vertical-align: text-top;
    }
    .IntegratedPayment_container.-privacy-policy{
        display: inline-block;
        text-align: center;
    }
    .IntegratedPayment_container.-privacy-policy a{
        color: #918f8f;
        font-size: 14px;
    }
    .IntegratedPayment_error {
        color: #E91932;
        font-size: 12px;
        margin: -10px 0 10px;
        width: 100%;
        line-height: 18px;
        padding-left: 4px;
    }
    .IntegratedPayment_error.-cardHolder {
        margin: -10px 0 0;
    }
    .IntegratedPayment_error.-exp, .IntegratedPayment_error.-cvv {
        width: 100%;
        max-width: calc(49%);
    }
    .IntegratedPayment_error.-cvv {
        justify-self: flex-end;
        margin: -10px 0 10px auto;
    }
    .-hide {
        display: none;
    }
    .IntegratedPayment_error.-payment, .IntegratedPayment_error.-fields, .IntegratedPayment_error.-api {
        display: none;
        background: rgba(233,25,50,0.08);
        color: #e91932;
        text-align: center;
        width: 100%;
        line-height: 18px;
        align-items: center;
        justify-content: center;
        margin: 10px 0 0;
        padding: 4px 0;
    }
    .IntegratedPayment_error.-payment.-show, .IntegratedPayment_error.-fields.-show, .IntegratedPayment_error.-api.-show {
        display: flex;
    }
    .IntegratedPayment_scheme {
        margin: 0;
    }
    .IntegratedPayment_schemes {
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-wrap: wrap;
        width: 115px;
    }
    .IntegratedPayment_scheme span {
        cursor: pointer;
        display: block;
        width: 33px;
        height: 22px;
        background: 50% no-repeat;
        background-size: 100% auto;
    }
    .IntegratedPayment_scheme span:before {
        display: block;
        width: 100%;
        height: 100%;
        content: "";
        background: 50% no-repeat;
        background-size: 100% auto;
        opacity: 0;
    }
    .IntegratedPayment_scheme input {
        display: none;
    }
    .IntegratedPayment_scheme input:checked + span:before {
        opacity: 1;
    }
    .IntegratedPayment_scheme.-visa span {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('visa-dark')); ?>');
    }
    .IntegratedPayment_scheme.-visa span:before {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('visa')); ?>');
    }
    .IntegratedPayment_scheme.-mastercard span {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('mastercard-dark')); ?>');
    }
    .IntegratedPayment_scheme.-mastercard span:before {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('mastercard')); ?>');
    }
    .IntegratedPayment_scheme.-cb span {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('cb-dark')); ?>');
    }
    .IntegratedPayment_scheme.-cb span:before {
        background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('cb')); ?>');
    }
    .IntegratedPayment .ipOverlay {
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        position: fixed;
        background-color: rgba(25,25,25,0.5);
        z-index: 100;
    }
    .IntegratedPayment .ipOverlay_inner {
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        position: absolute;
    }
    .IntegratedPayment .ipOverlay_content {
        left: 50%;
        position: absolute;
        top: 50%;
        transform: translate(-50%,-50%);
    }
    .IntegratedPayment .ipOverlay_spinner {
        width: 75px;
        height: 75px;
        display: inline-block;
        border-width: 2px;
        border-color: rgba(255,255,255,0.05);
        border-top-color: #fff;
        animation: spin 1s infinite linear;
        border-radius: 100%;
        border-style: solid;
        position: fixed;
        top: 50%;
        left: 50%;
    }
    @keyframes spin {
    .IntegratedPayment .ipOverlay 0% {
        transform: rotate(0deg);
    }
    .IntegratedPayment .ipOverlay 100% {
        transform: rotate(360deg);
    }
    }


</style>

<script>

    window.PAYPLUG_DOMAIN = "https://secure-qa.payplug.com";
    // Create an instance of IntegratedPayment


    var IntegratedPayment = {
        props: {
            cartId: null,
            paymentId: null,
            paymentOptionId: null,
            form: {},
            checkoutForm: null,
            api: null,
            integratedPayment: null,
            token: null,
            notValid: true,
            fieldsValid: {
                cardHolder: false,
                pan: false,
                cvv: false,
                exp: false,
            },
            fieldsEmpty: {
                cardHolder: true,
                pan: true,
                cvv: true,
                exp: true,
            },
            inputStyle:{
                default: {
                    color: '#2B343D',
                    fontFamily: 'Poppins, sans-serif',
                    fontSize: '14px',
                    textAlign: 'left',
                    '::placeholder': {
                        color: '#969a9f',
                    },
                    ':focus': {
                        color: '#2B343D',
                    }
                },
                invalid: {
                    color: '#E91932'
                }
            },
            save_card: false,
            scheme: null,
            query: null,
            submit: null,
            order_review: false,
            return_url: null
        },

        init: function(){
            IntegratedPayment.props.api = new Payplug.IntegratedPayment(false);
            IntegratedPayment.props.api.setDisplayMode3ds(Payplug.DisplayMode3ds.LIGHTBOX)

            // Add each payments fields
            IntegratedPayment.props.form.cardHolder = IntegratedPayment.props.api.cardHolder(document.querySelector('#cardholder-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder:'Name' } );
            IntegratedPayment.props.form.pan = IntegratedPayment.props.api.cardNumber(document.querySelector('#pan-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder:'Card Number' } );
            IntegratedPayment.props.form.cvv = IntegratedPayment.props.api.cvv(document.querySelector('#cvv-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder:'CVV' } );
            // With one field for expiration date
            IntegratedPayment.props.form.exp = IntegratedPayment.props.api.expiration(document.querySelector('#exp-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder:'Exp Date' } );

            IntegratedPayment.props.scheme = IntegratedPayment.props.api.getSupportedSchemes();

        },
    };




    window.addEventListener('checkout:payment:method-activate', (event) => {
        if (event.detail.method == "payplug_payments_standard") {

            hyvaCheckout.payment.activate('payplug_payments_standard', {


                async placeOrder(data, callback) {

                    console.log("placing order");

                    IntegratedPayment.props.api.validateForm();
                    IntegratedPayment.props.api.onValidateForm(({isFormValid}) => {
                        if (isFormValid) {





                                IntegratedPayment.props.api.onCompleted(async function (event) {
                                    console.log(event);
                                });
                            document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;

                            //hyvaCheckout.main.getWireComponent().placeOrder();

                        } else {
                            console.log(isFormValid+ ": form not valid");
                           // document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = true;
                        }
                    });

                },
                placeOrderViaJs() {
                    return true;
                },
                async initialize() {
                    console.log("intializing");
                    hyvaCheckout.navigation.addTask(async function () {

                       // hyvaCheckout.main.getWireComponent().placeOrder();

                        var response = await fetch('<?php echo $block->getBaseUrl();?>/payplug_payments/payment/standard?should_redirect=0&integrated=1');

                        var json = await response.json();
                        console.log(json);

                        IntegratedPayment.props.api.pay(json.payment_id, "AUTO");

                    });

                        if (document.querySelector('#payplug-js')) {
                            return;
                        }

                        const script = document.createElement('script');
                        script.src = 'https://cdn-qa.payplug.com/js/integrated-payment/v1@1/index.js';
                        script.setAttribute('id', 'payplug-js');

                        document.head.append(script);
                        script.addEventListener('load', () => {
                            if (!document.querySelector('#cardholder-input-container').hasChildNodes()) {
                                IntegratedPayment.init();
                                IntegratedPayment.props.api.validateForm();
                                IntegratedPayment.props.api.onValidateForm(({isFormValid}) => {
                                    if (isFormValid) {
                                        document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
                                    } else {
                                        document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = true;
                                    }
                                });
                            }
                        });


                },

                async validate() {
                    console.log("validation runing");
                    if (IntegratedPayment.props.api.validateForm()) {
                        document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
                    }
                }
            }, document.getElementById('payplug-payment-form'));


        } else {
            var script = document.getElementById("payplug-js");
            if (script) {
                script.remove();
            }
            document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
            hyvaCheckout.payment.method = null;
        }

    });



</script>
