<?php

/** @var Hyva\CheckoutPayplug\Magewire\ApplePay $magewire */
/** @var Hyva\CheckoutPayplug\Block\ApplePay $block */


?>
<div>
    <apple-pay-button buttonstyle="black" type="pay" locale="en"></apple-pay-button>
</div>


<script>
    window.addEventListener('checkout:payment:method-activate', (event) => {
        if (event.detail.method == "payplug_payments_apple_pay") {

            hyvaCheckout.payment.activate('payplug_payments_apple_pay', {

                initialize() {
                    this.loadHostedAPLib().then(async ()=>{
                        if(this.checkLoadedAP()){

                            document.querySelector('apple-pay-button').addEventListener('click', function() {
                                hyvaCheckout.payment.method.payApplePay();
                        });
                    }
                    });
                },
                payApplePay() {

                        console.log('clickedd ap');
                        let request = {
                            "countryCode": "<?= $magewire->getShipping()->getShippingAddress()->getCountryId(); ?>",
                            "currencyCode": "<?= $magewire->getShipping()->getData('quote_currency_code'); ?>",
                            "merchantCapabilities": [
                                "supports3DS"
                            ],
                            "supportedNetworks": [
                                "visa", "masterCard"
                            ],
                            "total": {
                                "label": "<?= $block->getConfig()['payment']['payplug_payments_apple_pay']['merchand_name'] ?>",
                                "type": "final",
                                "amount": '<?= $magewire->getShipping()->getData("grand_total"); ?>'
                            },
                            'applicationData': btoa(JSON.stringify({
                                'apple_pay_domain': '2ea5-85-184-72-98.ngrok-free.app'
                            }))
                        };
                        let session = new ApplePaySession(3, request);

                        console.log("session : " + JSON.stringify(session));
                        session.onvalidatemerchant = () => {
                            console.log("validate merchant");
                            fetch('<?php echo $block->getUrl("hyva_checkout_payplug/applepay/getTransactionData");?>').then(async response => {
                                let res = await response.json();
                                session.completeMerchantValidation(res.merchand_data);
                                console.log(JSON.stringify(res));
                            });
                        };
                        session.onpaymentauthorized = async (event) => {
                            //const body = new URLSearchParams({, 'token': JSON.stringify(});
                           // let data = event.payment.token;


                            const contentType = 'application/x-www-form-urlencoded; charset=UTF-8';
                            const body = new URLSearchParams({form_key: hyva.getFormKey(), token: JSON.stringify(event.payment.token)});
                            console.log("Token stringify : " + JSON.stringify(event.payment.token));
                            console.log("Token : " + JSON.stringify(event.payment.token));
                            fetch('<?php echo $block->getBaseUrl();?>hyva_checkout_payplug/applepay/updateTransaction', {
                                method: 'post',
                                body,
                                headers: {'Content-Type': contentType}
                            }).then(async response => {
                                let res = await response.json();
                                console.log(JSON.stringify(res));

                                let applePaySessionStatus = ApplePaySession.STATUS_SUCCESS;
                                if (response.error === true) {
                                    applePaySessionStatus = ApplePaySession.STATUS_FAILURE;
                                } else {
                                    session.completePayment({
                                        "status": applePaySessionStatus
                                    });
                                    console.log('payment completed is success: ' + ApplePaySession.STATUS_SUCCESS);
                                    console.log('payment completed : ' + applePaySessionStatus);
                                    window.location.replace('<?php echo $block->getBaseUrl();?>hyva_checkout_payplug/applepay/paymentReturn');
                                }

                            });
                        };
                        session.oncancel = event => {
                            console.log("payment cancel" + JSON.stringify(event));
                  //          window.location.replace('<?php echo $block->getBaseUrl();?>payplug_payments/payment/cancel');

                        };
                        session.begin();

                },
                loadHostedAPLib(){
                    return new Promise((resolve, reject) => {

                        if (!document.getElementById('apple_pay_cdn')) {
                            const script = document.createElement('script');
                            script.src = 'https://applepay.cdn-apple.com/jsapi/v1/apple-pay-sdk.js';
                            script.setAttribute('id', 'apple_pay_cdn');
                            document.head.append(script);
                        }



                        //if it's not loaded yet let's wait 100ms to load it
                        let count = 0;
                        const interval = setInterval(() => {
                            count++;
                            if (typeof ApplePaySession !== 'undefined') {
                                clearInterval(interval);
                                resolve();
                                return;
                            }

                            if (count > 100) {
                                reject();
                                clearInterval(interval);
                                throw new Error('Unable to load Apple Pay');
                            }
                        }, 100);
                    });
                },
                checkLoadedAP: function(){
                    return document.body.contains(document.querySelector('apple-pay-button'));
                }

            });


        } else {
            var script = document.getElementById("apple_pay_cdn");
            if (script) {
                script.remove();
            }
            document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
            hyvaCheckout.payment.method = null;
        }

    }, {once: true});
</script>
