<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Payplug\Payments\Block\Oney\Simulation;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Simulation $block */

$hasError = false;
$oneySimulation = $block->getOneySimulation();
$message = $oneySimulation->getMessage();

if (!$oneySimulation->getSuccess() || !empty($message)) {
    $hasError = true;
}

$isOneyWithoutFees = $oneySimulation->getMethod() === \Payplug\Payments\Gateway\Config\OneyWithoutFees::METHOD_CODE;
$pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);

/** @var PayplugIcons $viewModels */
$icons = $viewModels->require(PayplugIcons::class);
?>
<div data-oney-container="payplug_payments_oney">
    <div class="oneyPayment oneyPayment-open"></div>
</div>

<div class="payment-method-content"></div>

<style>
    <?php if($isOneyWithoutFees): ?>
        .oneyLogo-3x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('oney_without_fees/3x')); ?>');
        }

        .oneyLogo-4x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('oney_without_fees/4x')); ?>');
        }
    <?php else: ?>
        .oneyLogo-3x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('3x')); ?>');
        }

        .oneyLogo-4x {
            background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('4x')); ?>');
        }
    <?php endif; ?>
</style>

<script>
    var getOneyContainer = function() {
        return document.querySelector('[data-oney-container="payplug_payments_oney"]');
    }

    var getScheduleLabel = function (days) {
        var scheduleLabels = [
            {days: 30, label: "<?= $block->escapeHtml(__('In 30 days')); ?>" },
            {days: 60, label: "<?= $block->escapeHtml(__('In 60 days')); ?>" },
            {days: 90, label: "<?= $block->escapeHtml(__('In 90 days')); ?>" },
        ];

        let label = null;
        scheduleLabels.forEach(function(item) {
            if (item.days === days) {
                label = item.label;

                return false;
            }
        });

        return label;
    }

    var selectOneyOption = function(option) {
        const oneyPayment = getOneyContainer().querySelector('.oneyPayment');
        const oldSelected = oneyPayment.querySelector('.oneyOption-selected');

        if (oldSelected) {
            oldSelected.classList.remove('oneyOption-selected');
        }

        const selectedOption = getOneyContainer().querySelector('[data-type="'+ option +'"]');
        selectedOption.classList.add('oneyOption-selected');

        updatePlaceOrderButtonLabel(option);
    }

    var updatePlaceOrderButtonLabel= function(type) {
        var label;

        if (type === null) {
            label = "<?= __('Place Order'); ?>";
            hyva.replaceDomElement('.btn-primary[x-bind="buttonPlaceOrder()"]', '<button type="button" class="btn btn-primary\
            disabled:opacity-10\
            disabled:cursor-not-allowed\
            bg-green-600 hover:bg-green-500" x-spread="buttonPlaceOrder()" x-bind="buttonPlaceOrder()" data-step="{&quot;place&quot;:true}">\
            Valider la commande    </button>');
        } else {
            label = getPaymentTypeLabel().replace('%1', type);
            hyva.replaceDomElement('.btn-primary[x-bind="buttonPlaceOrder()"]', '<button type="button" class="btn btn-primary\
            disabled:opacity-10\
            disabled:cursor-not-allowed\
            bg-green-600 hover:bg-green-500" x-spread="buttonPlaceOrder()" x-bind="buttonPlaceOrder()" data-step="{&quot;place&quot;:true}">\
            '+label+'</button>');
        }
    }

    var getPaymentTypeLabel = function() {
      <?php if($isOneyWithoutFees): ?>
        return "<?= $block->escapeHtml(__('Payment in %1 without fees')) ;?>";

      <?php else: ?>
        return "<?= $block->escapeHtml(__('Payment in %1')) ;?>";
      <?php endif; ?>
    }

    var buildOneyDetail = function(){
        var tmpDiv = document.createElement('div');
        var optionsWrapper = document.createElement('div');
        optionsWrapper.classList.add('oneyOption_wrapper');

        var label = getPaymentTypeLabel();

        <?php if ($hasError): ?>
            var error_is_displayed = document.querySelector("p.oneyPopin_error");

            if (typeof(error_is_displayed) === 'undefined' || error_is_displayed === null ){
                var error_message = document.createElement('p');
                error_message.classList.add('oneyPopin_error');
                error_message.innerHTML = "<?= /* @noEscape */ $message; ?>";
                tmpDiv.appendChild(error_message);
            }
        <?php else: ?>
            <?php foreach ($oneySimulation->getOptions() as $option): ?>
                var type = "<?= $option->getType(); ?>";
                var option = document.createElement('label');

                option.setAttribute('data-type', type);
                option.classList.add('oneyOption', 'oneyOption-' + type);

                <?php // Title ?>
                var title =  document.createElement('div');
                title.classList.add('oneyOption_title');

                var tmpSpan = document.createElement('span');
                tmpSpan.classList.add('oneyOption_logo', 'oneyLogo', 'oneyLogo-' + type);

                title.append(tmpSpan);
                title.innerHTML += label.replace('%1', type);

                option.append(title);

                <?php if ($option->getSchedules()): ?>
                    var detail = document.createElement('div');
                    detail.classList.add('oneyOption_prices');

                    var list = document.createElement('ul');
                    list.classList.add('oneyOption_list');

                    var firstDeposit = document.createElement('li');
                    var totalAmoutSpan = document.createElement('span');

                    totalAmoutSpan.innerHTML += "<?= __('Total order amount'); ?>";
                    firstDeposit.append(totalAmoutSpan);

                    var oneyOptionSpan = document.createElement('span');

                    oneyOptionSpan.classList.add('oneyOption_price');
                    oneyOptionSpan.innerHTML += "<?= /* @noEscape */ $pricingHelper->currency($option->getFirstDeposit(), true, false); ?>";
                    firstDeposit.append(oneyOptionSpan);
                    list.append(firstDeposit);

                    var daysForPayment = 30;

                    <?php foreach ($option->getSchedules() as $i => $schedule): ?>
                        var scheduleData = "<?= $block->escapeHtml(__(sprintf('Installment %d:', $i + 1))); ?>";
                        var schedule = document.createElement('li');
                        var daysSpan = document.createElement('span');

                        daysSpan.innerHTML += getScheduleLabel(daysForPayment);
                        schedule.append(daysSpan);

                        var oneyOptionSpan2 = document.createElement('span');

                        oneyOptionSpan2.classList.add('oneyOption_price');
                        oneyOptionSpan2.innerHTML += "<?= /* @noEscape */ $pricingHelper->currency($schedule->getAmount(), true, false); ?>";
                        schedule.append(oneyOptionSpan2);
                        list.append(schedule);
                        daysForPayment += 30;
                    <?php endforeach; ?>

                    var totalAmout = document.createElement('li');
                    var totalCostSpanLabel = document.createElement('span');
                    totalCostSpanLabel.innerHTML += "<?= __('Total cost') ?>";

                    var totalCostSpan = document.createElement('span');
                    totalCostSpan.classList.add('oneyOption_price');
                    totalCostSpan.innerHTML += "<?= /* @noEscape */ $pricingHelper->currency($option->getTotalAmount(), true, false); ?>";

                    totalAmout.append(totalCostSpanLabel);
                    totalAmout.append(totalCostSpan);

                    list.append(totalAmout);
                    detail.append(list);
                    option.append(detail);
                <?php endif; ?>

                var radio = document.createElement('div');
                var radioDiv = document.createElement('div');
                var radioSpan = document.createElement('span');
                var radioInput = document.createElement('input');

                radioInput.setAttribute('type', 'radio');
                radioInput.setAttribute('name', 'oney_type');
                radioInput.value = type;

                radioSpan.append(radioInput);

                radio.classList.add('oneyOption_radio');
                radioDiv.classList.add('radio');
                radioDiv.append(radioSpan);
                radio.append(radioSpan);

                option.append(radio);
                optionsWrapper.append(option);
            <?php endforeach; ?>
        <?php endif; ?>

        tmpDiv.appendChild(optionsWrapper);
        getOneyContainer().querySelector('.oneyPayment').appendChild(tmpDiv);
    }

    var oney_type = '';

    window.addEventListener('checkout:payment:method-activate', (event) => {
        if (event.detail.method == 'payplug_payments_oney' || event.detail.method == 'payplug_payments_oney_without_fees') {
            switch (event.detail.method){
                case 'payplug_payments_oney':
                    oney_type = 'payplug_payments_oney';
                    break;
                case 'payplug_payments_oney_without_fees':
                    oney_type = 'payplug_payments_oney_without_fees';
                    break;
                default:
                    oney_type = 'payplug_payments_oney';
        }

        hyvaCheckout.payment.activate(oney_type, {
            validate() {
                return new Promise(async (resolve, reject) => {
                    var selected = document.querySelector('input[name="oney_type"]:checked');
                    var option = await Magewire.find('checkout.payment.method.' + oney_type).call('setOneyType', selected.value);
                        resolve();
                    });
                }
            }, document.getElementById('payment-method-view-' + oney_type));

            var oney = document.querySelector('.oneyOption_wrapper');

            if (oney) {
                document.querySelector('.oneyOption_wrapper').remove();
                buildOneyDetail();
            } else {
                buildOneyDetail();
            }

            if (document.querySelector('.oneyOption_wrapper .oneyOption-3x') ){
                document.querySelector('.oneyOption_wrapper .oneyOption-3x').addEventListener('click', function () {
                    var selected = document.querySelector('input[name="oney_type"]:checked');
                    selectOneyOption(selected.value);
                });
            }

            if (document.querySelector('.oneyOption_wrapper .oneyOption-4x') ) {
                document.querySelector('.oneyOption_wrapper .oneyOption-4x').addEventListener('click', function () {
                    var selected = document.querySelector('input[name="oney_type"]:checked');
                    selectOneyOption(selected.value);
                });
            }
        }
    });
</script>
