<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\CheckoutPayplug\Magewire\ApplePay;
use Hyva\CheckoutPayplug\Block\ApplePay as ApplePayBlock;
use Magento\Framework\Escaper;

/** @var ApplePay $magewire */
/** @var ApplePayBlock $block */
/** @var Escaper $escaper */
?>

<div wire:ignore>
    <apple-pay-button 
        buttonstyle="black" 
        type="pay" 
        locale="en"
    ></apple-pay-button>

    <div id="pp-apple-pay-payment"
         data-shipping-country-id="<?= $escaper->escapeHtmlAttr($magewire->getShipping()->getShippingAddress()->getCountryId()); ?>"
         data-shipping-currrency="<?= $escaper->escapeHtmlAttr($magewire->getShipping()->getData('quote_currency_code')); ?>"
         data-merchant-name="<?= $escaper->escapeHtmlAttr($block->getConfig()['payment']['payplug_payments_apple_pay']['merchand_name']); ?>"
         data-total="<?= $escaper->escapeHtmlAttr($magewire->getShipping()->getData("grand_total")); ?>"
         data-domain="<?= $escaper->escapeHtmlAttr($block->getConfig()['payment']['payplug_payments_apple_pay']['domain']); ?>"
     ></div>
</div>
