<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Payplug\Payments\Block\Oney\Simulation;
use Magento\Framework\Pricing\Helper\Data;
use Payplug\Payments\Gateway\Config\OneyWithoutFees;

/** @var Escaper $escaper */
/** @var PayplugIcons $viewModels */
/** @var Simulation $block */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$hasError = false;
$oneySimulation = $block->getOneySimulation();
$message = $oneySimulation->getMessage();

if (!$oneySimulation->getSuccess() || !empty($message)) {
    $hasError = true;
}

$oneyType = $oneySimulation->getMethod();
$isOneyWithoutFees = $oneySimulation->getMethod() === OneyWithoutFees::METHOD_CODE;
$pricingHelper = $this->helper(Data::class);
$icons = $viewModels->require(PayplugIcons::class);

$oney3xLogo = $icons->renderHtml('oney/3x' . ($isOneyWithoutFees ? '-without-fees' : ''), '', 150, 32, ['aria-hidden' => 'true']);
$oney4xLogo = $icons->renderHtml('oney/4x' . ($isOneyWithoutFees ? '-without-fees' : ''), '', 150, 32, ['aria-hidden' => 'true']);
?>

<div wire:ignore>
    <span id="message" class="text-gray-500 font-medium text-sm"></span>
    <div id="oney-payment" class="oney-payment oney-payment-open"></div>
    <div class="payment-method-content"></div>
    <span class="oney-popin <?php if ($hasError): ?>oney-popin-error<?php endif; ?>"></span>

    <?php
        $options = array_map(static function($option) use ($pricingHelper) {
            $schedules = $option->getSchedules();
            $keys = array_keys($schedules);

            return [
                'type' => $option->getType(),
                'firstDeposit' => $pricingHelper->currency($option->getFirstDeposit(), true, false),
                'totalAmount' => $pricingHelper->currency($option->getTotalAmount(), true, false),

                'schedules' => array_map(static function($schedule, $i) use ($pricingHelper) {
                    return [
                        'amount' => $pricingHelper->currency($schedule->getAmount(), true, false),
                    ];
                }, $schedules, $keys),
            ];
        }, $oneySimulation->getOptions() ?? []);
    ?>

    <div id="pp-oney-payment"
        data-label="<?= $escaper->escapeHtmlAttr(__($isOneyWithoutFees ? 'Payment in %1 without fees' : 'Payment in %1')) ?>"
        data-has-error="<?= $escaper->escapeHtmlAttr($hasError ? 'true' : 'false') ?>"
        data-message="<?= $escaper->escapeHtmlAttr($message) ?>"
        data-options="<?= $escaper->escapeHtmlAttr(json_encode($options)) ?>"
        data-type="<?= $escaper->escapeHtmlAttr($oneyType) ?>"
        data-logo-three-times="<?= $escaper->escapeHtmlAttr($oney3xLogo) ?>"
        data-logo-four-times="<?= $escaper->escapeHtmlAttr($oney4xLogo) ?>"
    ></div>
</div>
