<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Payplug\PaymentsHyvaCheckout\Magewire\Ppro;
use Magento\Framework\Escaper;

/** @var Ppro $magewire */
/** @var Escaper $escaper */
?>

<div>
    <span id="message" class="text-gray-500 font-medium text-sm"></span>

    <div id="pp-ppro-payment"
         data-billing-country-id="<?= $escaper->escapeHtmlAttr($magewire->getQuote()->getBillingAddress()->getCountryId()) ?>"     
         data-shipping-country-id="<?= $escaper->escapeHtmlAttr($magewire->getQuote()->getShippingAddress()->getCountryId()) ?>"
         data-method="<?= $escaper->escapeHtmlAttr($magewire->getQuote()->getPayment()->getMethod()) ?>"
    ></div>
</div>
