<?php

declare(strict_types=1);

/** @var Magento\Catalog\Block\Product\View $block */

$price = $block->getProduct()->getFinalPrice(1);
$containerCssClasses = $block->getContainerCssClasses();
?>
<div class="oney-wrapper oney-product <?= $escaper->escapeHtmlAttr($containerCssClasses); ?>">
    <?= $block->getChildBlock('payplug-payments-product-oney-simulation')
            ->setAmount($price)
            ->toHtml();
    ?>
</div>
