<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Payplug\Payments\Block\Oney\Simulation;
use Magento\Framework\Pricing\Helper\Data;
use Payplug\Payments\Gateway\Config\OneyWithoutFees;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Simulation $block */

$hasError = false;
$oneySimulation = $block->getOneySimulation();
$message = $oneySimulation->getMessage();

if (!$oneySimulation->getSuccess() || !empty($message)) {
    $hasError = true;
}

$oneyType = $oneySimulation->getMethod();
$isOneyWithoutFees = $oneySimulation->getMethod() === OneyWithoutFees::METHOD_CODE;
$pricingHelper = $this->helper(Data::class);

/** @var PayplugIcons $viewModels */
$icons = $viewModels->require(PayplugIcons::class);
?>

<div>
    <div data-oney-container="payplug_payments_oney">
        <div id="oney-payment" class="oney-payment oney-payment-open"></div>
    </div>

    <div class="payment-method-content"></div>

    <span class="oney-popin <?php if ($hasError): ?>oney-popin-error<?php endif; ?>"></span>

    <style>
        <?php if($isOneyWithoutFees): ?>
            .oneyLogo-3x {
                background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('oney_without_fees/3x')); ?>');
            }
            .oneyLogo-4x {
                background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('oney_without_fees/4x')); ?>');
            }
        <?php else: ?>
            .oneyLogo-3x {
                background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('3x')); ?>');
            }
            .oneyLogo-4x {
                background-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('4x')); ?>');
            }
        <?php endif; ?>
    </style>

    <?php
        $options = array_map(static function($option) use ($pricingHelper) {
            $schedules = $option->getSchedules();
            $keys = array_keys($schedules);

            return [
                'type' => $option->getType(),
                'firstDeposit' => $pricingHelper->currency($option->getFirstDeposit(), true, false),
                'totalAmount' => $pricingHelper->currency($option->getTotalAmount(), true, false),

                'schedules' => array_map(static function($schedule, $i) use ($pricingHelper) {
                    return [
                        'amount' => $pricingHelper->currency($schedule->getAmount(), true, false),
                    ];
                }, $schedules, $keys),
            ];
        }, $oneySimulation->getOptions() ?? []);
    ?>

    <div x-data="magewireOneyPayment"
        data-label="<?= $escaper->escapeHtmlAttr(__($isOneyWithoutFees ? 'Payment in %1 without fees' : 'Payment in %1')) ?>"
        data-has-error="<?= $escaper->escapeHtmlAttr($hasError ? 'true' : 'false') ?>"
        data-message="<?= $escaper->escapeHtmlAttr($message) ?>"
        data-options="<?= $escaper->escapeHtmlAttr(json_encode($options)) ?>"
        data-type="<?= $escaper->escapeHtmlAttr($oneyType) ?>"
    ></div>
</div>
