<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
?>

<script>
    function magewirePpro() {
        return {
            ['initMagewirePpro']() {
                const { 
                    billingCountryId, 
                    shippingCountryId,
                    method
                } = this.$el.dataset;

                (() => {
                    window.addEventListener('checkout:payment:method-activate', (event) => {
                        let data = {
                            'billingCountry': billingCountryId,
                            'shippingCountry': shippingCountryId,
                            'paymentMethod': method,
                        };
                        const body = new URLSearchParams(data);
                        fetch('<?= $escaper->escapeUrl($block->getUrl("payplug_payments/ppro/isAvailable")); ?>' + '?form_key=' + hyva.getFormKey(), {
                            method: 'post',
                            body,
                            headers: {'contentType': 'application/x-www-form-urlencoded', 'accept': 'application/json'}
                        }).then(async response => {
                            let res = await response.json();
                            if (typeof res.data != "undefined" && typeof res.data.message != "undefined") {
                                document.getElementById('message').textContent = res.data.message;
                            }
                        });
                    }, { once: true });
                })();
            }
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('magewirePpro', magewirePpro)
    }, { once: true });
</script>

<?php $hyvaCsp->registerInlineScript() ?>
