<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\CheckoutPayplug\Block\Standard;
use Hyva\CheckoutPayplug\Magewire\Ppro;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Ppro $magewire */
/** @var Escaper $escaper */
/** @var Standard $block */

$icons = $viewModels->require(PayplugIcons::class);
?>
<div>
    <span id="message" class="text-gray-500 font-medium text-sm"></span>

    <div x-data="srcViewFrontendTemplatesMagewirePpro"
         x-init="srcViewFrontendTemplatesMagewirePproInit1"

         data-shipping-country-id="<?= $escaper->escapeHtmlAttr($magewire->getQuote()->getShippingAddress()->getCountryId()) ?>"
         data-shipping-country-id="<?= $escaper->escapeHtmlAttr($magewire->getQuote()->getShippingAddress()->getCountryId()) ?>"
         data-method="<?= $escaper->escapeHtmlAttr($magewire->getQuote()->getPayment()->getMethod()) ?>"
    ></div>
</div>
