<?php

declare(strict_types=1);

use Hyva\CheckoutPayplug\Block\Standard as BlockStandard;
use Hyva\CheckoutPayplug\Model\Magewire\Payment\Method\Standard as MethodStandard;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;

/** @var BlockStandard $block */
/** @var Escaper $escaper */
/** @var MethodStandard $magewire */
/** @var StoreConfig $storeConfigViewModel */
/** @var ViewModelRegistry $viewModels */

$storeConfigViewModel = $viewModels->require(StoreConfig::class);
$config = $block->getConfig();
$icons = $viewModels->require(PayplugIcons::class);

$storeCode = $storeConfigViewModel->getStoreConfig('general/locale/code');
$paymentConfig = $config['payment'];
$payplugCards = $block->getPayplugCards();
$cbName = $storeCode === 'it_IT' ? 'postepay' : 'cb';

$isIntegrated = false;
$isOneClick = false;
$isPopup = false;
$isRedirected = false;

if (isset($paymentConfig["payplug_payments_standard"])) {
    $isIntegrated = $paymentConfig["payplug_payments_standard"]["is_integrated"];
    $isOneClick = $paymentConfig["payplug_payments_standard"]["is_one_click"];
    $isPopup = $paymentConfig["payplug_payments_standard"]["is_embedded"];
    $isRedirected = !$isPopup && !$isIntegrated;
}
?>

<div>
    <?php // Prepaid card ?>
    <?php if (!empty($payplugCards) && $isOneClick) : ?>
        <ul class="pl-5 space-y-4" id="payplug-payments-cards">
            <?php foreach ($payplugCards as $payplugCard) : ?>
                <?php
                    $customerCardId = $payplugCard->getCustomerCardId();
                    $cardBrand = $payplugCard->getBrand();
                    $cardFourDigits = $payplugCard->getLastFour();
                    $date = $payplugCard->getExpDate();
                    $cardExpirationDate = $block->getFormattedExpDate($date);
                ?>
                <li class="flex items-center gap-x-2.5">
                    <input type="radio"
                           name="payment[payplug_payments_standard][customer_card_id]" 
                           id="payplug_payments_card_<?= $escaper->escapeHtmlAttr($customerCardId); ?>" 
                           class="payplug-payments-customer-card"
                           data-card-id="<?= $escaper->escapeHtmlAttr($customerCardId); ?>"
                           value="<?= $escaper->escapeHtmlAttr($customerCardId); ?>" />
                    <label for="payplug_payments_card_<?= $escaper->escapeHtmlAttr($customerCardId); ?>" class="mb-0">
                        <img src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('other')); ?>"
                             class="inline"
                             width="24"
                             height="24"
                             alt="" />
                        <span class="font-bold">
                            **** **** **** <?= $escaper->escapeHtml($cardFourDigits); ?>
                            <span class="font-normal">(<?= $escaper->escapeHtml($cardExpirationDate); ?>)</span>
                        </span>
                    </label>
                </li>
            <?php endforeach ?>
            <li class="flex items-center gap-x-2.5">
                <input type="radio"
                       name="payment[payplug_payments_standard][customer_card_id]" 
                       id="other-card"
                       class="payplug-payments-customer-card" 
                       value="" />
                <label for="other-card" class="mb-0">
                    <?= $escaper->escapeHtml(__('Pay with another card')); ?>
                </label>
            </li>
        </ul>
    <?php endif; ?>

    <?php if ($isIntegrated) : ?>
        <div id="payplug-payment-form"
             class="payplug pp-integrated-payment -loaded <?= !empty($payplugCards) && $isOneClick ? 'ml-[46px] pt-3 -hide' : '' ?>"
             wire:ignore>
            <div id="cardholder-input-container" class="payplug pp-integrated-payment_container -cardHolder cardHolder-input-container" data-e2e-name="cardHolder">
            </div>
            <div class="error-container cardholder-input-container">
                <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid Name and/or Last Name.')); ?></span></div>
                <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
            </div>
            <div class="payplug pp-integrated-payment_container -scheme">
                <div>
                    <?= $escaper->escapeHtml(__('Your card')); ?>
                </div>
                <div x-data="integratedStandardPayment"
                     class="flex justify-between items-center flex-wrap w-[115px]">
                    <label class="hover:cursor-pointer">
                        <span class="sr-only">Visa</span>
                        <span :class="visaCardClass" x-cloak>
                            <?= $icons->renderHtml('visa', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <span :class="visaCardDarkClass">
                            <?= $icons->renderHtml('visa-dark', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <input type="radio"
                               class="sr-only"
                               name="schemeOptions"
                               value="visa"
                               :value="currentCard" 
                               @change="handleInputChange()" />
                    </label>
                    <label class="hover:cursor-pointer">
                        <span class="sr-only">Mastercard</span>
                        <span :class="masterCardClass" x-cloak>
                            <?= $icons->renderHtml('mastercard', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <span :class="masterCardDarkClass">
                            <?= $icons->renderHtml('mastercard-dark', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <input type="radio"
                               class="sr-only"
                               name="schemeOptions"
                               value="mastercard"
                               :value="currentCard" 
                               @change="handleInputChange()" />
                    </label>
                    <label class="hover:cursor-pointer">
                        <span class="sr-only">
                            <?= $escaper->escapeHtml($storeCode === 'it_IT' ? 'PostePay' : 'CB') ?>
                        </span>
                        <span :class="cbCardClass" x-cloak>
                            <?= $icons->renderHtml($cbName, 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <span :class="cbCardDarkClass">
                        <?= $icons->renderHtml($cbName . '-dark', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <input type="radio"
                               class="sr-only"
                               name="schemeOptions"
                               value="cb"
                               :value="currentCard" 
                               @change="handleInputChange()" />
                    </label>
                </div>
            </div>
            <div id="pan-input-container" class="payplug pp-integrated-payment_container -pan pan-input-container" data-e2e-name="pan"></div>
            <div class="error-container pan-input-container">
                <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid card number.')); ?></span></div>
                <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
            </div>
            <div class="exp-cvv-container">
                <div>
                    <div id="exp-input-container" class="payplug pp-integrated-payment_container -exp exp-input-container" data-e2e-name="expiration"></div>
                    <div class="error-container exp-input-container">
                        <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid expiration date.')); ?></span></div>
                        <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
                    </div>
                </div>

                <div>
                    <div id="cvv-input-container" class="payplug pp-integrated-payment_container -cvv cvv-input-container" data-e2e-name="cvv"></div>
                    <div class="error-container cvv-input-container">
                        <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid CVV.')); ?></span></div>
                        <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
                    </div>
                </div>
            </div>
            <?php if ($paymentConfig["payplug_payments_standard"]['is_one_click']) : ?>
                <div class="save-card-container">
                    <input type="checkbox" name="save_card" id="payplug_save_card">
                    <label for="payplug_save_card" class="inline align-middle"><?= $escaper->escapeHtml(__('Save my credit card')); ?></label>
                </div>
            <?php endif; ?>

            <div class="transaction-secured">
                <img src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>" alt="">
                <span><?= $escaper->escapeHtml(__('Transaction secured by')); ?></span>
                <img class="payplug-logo" src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('payplug')); ?>" alt="">
            </div>
        </div>

        <style>
            .pp-integrated-payment_container.-cardHolder::before {
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
            }

            .pp-integrated-payment_container.-pan::before {
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
            }

            .pp-integrated-payment_container.-exp,
            .pp-integrated-payment_container.-cvv {
                display: block;
                max-width: calc(140px);
            }

            .pp-integrated-payment_container.-cvv::before {
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
            }

            .pp-integrated-payment_container.-exp::before {
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
            }
        </style>
    <?php endif; ?>

    <div x-data="magewireStandardPayment"
         data-is-one-click="<?= !empty($payplugCards) && $isOneClick ? 'true' : 'false' ?>"
         data-is-integrated="<?= $isIntegrated ? 'true' : 'false' ?>"
         data-is-redirected="<?= $isRedirected ? 'true' : 'false' ?>"
         data-is-popup="<?= $isPopup ? 'true' : 'false' ?>"
         data-is-sandbox="<?= $escaper->escapeHtmlAttr($paymentConfig['payplug_payments_standard']['is_sandbox']); ?>"
    ></div>
</div>
