<?php

declare(strict_types=1);

use Hyva\CheckoutPayplug\Block\Standard as BlockStandard;
use Hyva\CheckoutPayplug\Model\Magewire\Payment\Method\Standard as MethodStandard;
use Hyva\CheckoutPayplug\ViewModel\PayplugIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;

/** @var BlockStandard $block */
/** @var Escaper $escaper */
/** @var MethodStandard $magewire */
/** @var StoreConfig $storeConfigViewModel */
/** @var ViewModelRegistry $viewModels */

$storeConfigViewModel = $viewModels->require(StoreConfig::class);
$config = $block->getConfig();
$icons = $viewModels->require(PayplugIcons::class);

$storeCode = $storeConfigViewModel->getStoreConfig('general/locale/code');
$paymentConfig = $config['payment'];
$payplugCards = $block->getPayplugCards();

$integrated = false;
$isOneClick = false;

if (isset($paymentConfig["payplug_payments_standard"])) {
    $integrated = $paymentConfig["payplug_payments_standard"]["is_integrated"];
    $isOneClick = $paymentConfig["payplug_payments_standard"]["is_one_click"];
}
?>

<div>
    <?php if (!empty($payplugCards) && $isOneClick) : ?>
        <ul class="payplug-payments-cards">
            <?php foreach ($payplugCards as $payplugCard) : ?>
                <?php
                $customerCardId = $payplugCard->getCustomerCardId();
                $cardBrand = $payplugCard->getBrand();
                $cardFourDigits = $payplugCard->getLastFour();
                $date = $payplugCard->getExpDate();
                $cardExpirationDate = $block->getFormattedExpDate($date);
                ?>
                <li>
                    <input type="radio" 
                           name="payment[payplug_payments_standard][customer_card_id]" 
                           id="payplug_payments_card_<?= $escaper->escapeHtmlAttr($customerCardId); ?>" 
                           class="payplug-payments-customer-card"
                           data-card-id="<?= $escaper->escapeHtmlAttr($customerCardId); ?>"
                           value="<?= $escaper->escapeHtmlAttr($customerCardId); ?>" />
                    <label for="payplug_payments_card_<?= $escaper->escapeHtmlAttr($customerCardId); ?>">
                        <img src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('other')); ?>" alt="">
                        <span class="card-last4"> <b>**** **** **** <?= $escaper->escapeHtml($cardFourDigits); ?></b></span>
                        <span>(<?= $escaper->escapeHtml($cardExpirationDate); ?>)</span>
                    </label>
                </li>
            <?php endforeach; ?>
            <li>
                <input type="radio" 
                       name="payment[payplug_payments_standard][customer_card_id]" 
                       id="payplug_payments_card_" 
                       class="payplug-payments-customer-card" 
                       value="" />
                <label for="payplug_payments_card_">
                    <?= $escaper->escapeHtml(__('Pay with another card')); ?>
                </label>
            </li>
        </ul>
    <?php endif; ?>

    <?php if ($integrated) : ?>
        <div id="payplug-payment-form" class="payplug IntegratedPayment -loaded <?= !empty($payplugCards) && $isOneClick ? '-hide' : '' ?>">
            <div id="cardholder-input-container" class="payplug IntegratedPayment_container -cardHolder cardHolder-input-container" data-e2e-name="cardHolder">
            </div>
            <div class="error-container cardholder-input-container">
                <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid Name and/or Last Name.')); ?></span></div>
                <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
            </div>
            <div class="payplug IntegratedPayment_container -scheme">
                <div>
                    <?= $escaper->escapeHtml(__('Your card')); ?>
                </div>
                <div x-data="{ currentCard: '' }"
                     class="flex justify-between items-center flex-wrap w-[115px]">
                    <label class="hover:cursor-pointer">
                        <span class="sr-only">Visa</span>
                        <span :class="currentCard === 'visa' ? 'inline' : 'hidden'" x-cloak>
                            <?= $icons->renderHtml('visa', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <span :class="currentCard === 'visa' ? 'hidden' : 'inline'">
                            <?= $icons->renderHtml('visa-dark', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <input type="radio"
                               class="sr-only"
                               name="schemeOptions"
                               value="visa"
                               x-model="currentCard" />
                    </label>
                    <label class="hover:cursor-pointer">
                        <span class="sr-only">Mastercard</span>
                        <span :class="currentCard === 'mastercard' ? 'inline' : 'hidden'" x-cloak>
                            <?= $icons->renderHtml('mastercard', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <span :class="currentCard === 'mastercard' ? 'hidden' : 'inline'">
                            <?= $icons->renderHtml('mastercard-dark', 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <input type="radio"
                               class="sr-only"
                               name="schemeOptions"
                               value="mastercard"
                               x-model="currentCard" />
                    </label>
                    <label class="hover:cursor-pointer">
                        <span class="sr-only">CB</span>
                        <span :class="currentCard === 'cb' ? 'inline' : 'hidden'" x-cloak>
                            <?php $cbName = $storeCode === 'it_IT' ? 'cb-it' : 'cb' ?>
                            <?= $icons->renderHtml($cbName, 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <span :class="currentCard === 'cb' ? 'hidden' : 'inline'">
                        <?php $cbDarkName = $storeCode === 'it_IT' ? 'cb-dark-it' : 'cb-dark' ?>
                        <?= $icons->renderHtml($cbDarkName, 'w-payment-card h-payment-card', 33, 22, ['aria-hidden' => 'true']); ?>
                        </span>
                        <input type="radio"
                               class="sr-only"
                               name="schemeOptions"
                               value="cb"
                               x-model="currentCard" />
                    </label>
                </div>
            </div>
            <div id="pan-input-container" class="payplug IntegratedPayment_container -pan pan-input-container" data-e2e-name="pan"></div>
            <div class="error-container pan-input-container">
                <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid card number.')); ?></span></div>
                <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
            </div>
            <div class="exp-cvv-container">
                <div>
                    <div id="exp-input-container" class="payplug IntegratedPayment_container -exp exp-input-container" data-e2e-name="expiration"></div>
                    <div class="error-container exp-input-container">
                        <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid expiration date.')); ?></span></div>
                        <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
                    </div>
                </div>

                <div>
                    <div id="cvv-input-container" class="payplug IntegratedPayment_container -cvv cvv-input-container" data-e2e-name="cvv"></div>
                    <div class="error-container cvv-input-container">
                        <div class="invalid-field"><span><?= $escaper->escapeHtml(__('Invalid CVV.')); ?></span></div>
                        <div class="empty-field"><span><?= $escaper->escapeHtml(__('Mandatory field.')); ?></span></div>
                    </div>
                </div>
            </div>
            <?php if ($paymentConfig["payplug_payments_standard"]['is_one_click']) : ?>
                <div class="save-card-container">
                    <input type="checkbox" name="save_card" id="payplug_save_card">
                    <label for="payplug_save_card"><?= $escaper->escapeHtml(__('Save my credit card')); ?></label>
                </div>
            <?php endif; ?>

            <div class="transaction-secured">
                <img src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>" alt="">
                <span><?= $escaper->escapeHtml(__('Transaction secured by')); ?></span>
                <img class="payplug-logo" src="data:image/svg+xml,<?= rawurlencode($icons->renderHtml('payplug')); ?>" alt="">
            </div>
        </div>

        <style>
            .IntegratedPayment_container.-cardHolder::before {
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('account')); ?>');
            }

            .IntegratedPayment_container.-pan::before {
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('card')); ?>');
            }

            .IntegratedPayment_container.-exp,
            .IntegratedPayment_container.-cvv {
                display: block;
                max-width: calc(140px);
            }

            .IntegratedPayment_container.-cvv::before {
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('lock')); ?>');
            }

            .IntegratedPayment_container.-exp::before {
                mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
                -webkit-mask-image: url('data:image/svg+xml,<?= rawurlencode($icons->renderHtml('calendar')); ?>');
            }
        </style>
    <?php endif; ?>

    <script>
        (() => {
            var oneclick = <?= !empty($payplugCards) && $isOneClick ? 1 : 0; ?>;
            var integrated = <?= $integrated ? 1 : 0; ?>;

            if (integrated) {
                var IntegratedPayment = {
                    props: {
                        cartId: null,
                        paymentId: null,
                        paymentOptionId: null,
                        form: {},
                        checkoutForm: null,
                        api: null,
                        integratedPayment: null,
                        token: null,
                        notValid: true,
                        fieldsValid: {
                            cardHolder: false,
                            pan: false,
                            cvv: false,
                            exp: false,
                        },
                        fieldsEmpty: {
                            cardHolder: true,
                            pan: true,
                            cvv: true,
                            exp: true,
                        },
                        inputStyle: {
                            default: {
                                color: '#2B343D',
                                fontFamily: 'Poppins, sans-serif',
                                fontSize: '14px',
                                textAlign: 'left',
                                '::placeholder': {
                                    color: '#969a9f',
                                },
                                ':focus': {
                                    color: '#2B343D',
                                }
                            },
                            invalid: {
                                color: '#E91932'
                            }
                        },
                        save_card: false,
                        scheme: null,
                        query: null,
                        submit: null,
                        order_review: false,
                        return_url: null
                    },
                    init: function () {
                        IntegratedPayment.props.api = new Payplug.IntegratedPayment(<?= $escaper->escapeJs($paymentConfig['payplug_payments_standard']['is_sandbox']); ?>);
                        IntegratedPayment.props.api.setDisplayMode3ds(Payplug.DisplayMode3ds.LIGHTBOX);
                        IntegratedPayment.props.form = {};
                        IntegratedPayment.props.form.cardHolder = {element: IntegratedPayment.props.api.cardHolder(document.querySelector('#cardholder-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'Name'})};
                        IntegratedPayment.props.form.pan = {element:IntegratedPayment.props.api.cardNumber(document.querySelector('#pan-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'Card Number'})};
                        IntegratedPayment.props.form.cvv = {element:IntegratedPayment.props.api.cvv(document.querySelector('#cvv-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'CVV'})};
                        IntegratedPayment.props.form.exp = {element:IntegratedPayment.props.api.expiration(document.querySelector('#exp-input-container'), {default: IntegratedPayment.props.inputStyle.default, placeholder: 'Exp Date'})};
                        IntegratedPayment.props.scheme = IntegratedPayment.props.api.getSupportedSchemes();
                    },
                };
            }

            window.addEventListener('checkout:payment:method-activate', (event) => {

                if (event.detail.method == "payplug_payments_standard") {
                    hyvaCheckout.payment.activate('payplug_payments_standard', {
                        initialize() {
                            if (integrated) {
                                this.loadHostedLib().then(() => {
                                    if (!this.checkLoaded()) {
                                        IntegratedPayment.init();
                                    }
                                });
                            }
                        },
                        async validate() {
                            var card_selected = false;
                            if (document.querySelector('input[name="payment[payplug_payments_standard][customer_card_id]"]:checked') != null) {
                                if (document.querySelector('input[name="payment[payplug_payments_standard][customer_card_id]"]:checked').value) {
                                    card_selected = true;
                                }
                            }
                            if (oneclick && card_selected) {
                                var selected = document.querySelector('input[name="payment[payplug_payments_standard][customer_card_id]"]:checked');
                                await Magewire.find('checkout.payment.method.payplug_payments_standard').call('setAditionalData', selected.value);
                                hyvaCheckout.main.getWireComponent().placeOrder();
                                resolve();

                                return true;
                            } else {
                                if (integrated) {
                                    hyvaCheckout.evaluation.registerExecutable('make:pay-plug:payment', async () => {
                                        // Just simulating a 5 seconds API request.
                                        return new Promise((resolve) => {
                                            IntegratedPayment.props.api.setDisplayMode3ds(Payplug.DisplayMode3ds.LIGHTBOX);
                                            IntegratedPayment.props.api.validateForm()
                                            IntegratedPayment.props.api.onValidateForm(({isFormValid}) => {
                                                magewire.plugins.loader.start();
                                                if (isFormValid) {
                                                    fetch('<?= $escaper->escapeUrl($block->getUrl("payplug_payments/payment/standard", ['_query' => ['should_redirect' => '0', 'integrated' => '1']])); ?>').then(response => {
                                                        let res = response.clone().json();
                                                        res.then(result => {
                                                            if (typeof result.error !== 'undefined' && result.error) {
                                                                window.location.replace(response.url);
                                                                reject();

                                                            } else {
                                                                if (typeof result.payment_id !== undefined && result.payment_id) {
                                                                    let save_card = false;
                                                                    if (document.querySelector("#payplug_save_card") != null &&
                                                                        typeof document.querySelector("#payplug_save_card") != "undefined" &&
                                                                        document.querySelector("#payplug_save_card").checked) {
                                                                        save_card = true;
                                                                    }

                                                                    IntegratedPayment.props.api.pay(result.payment_id, 0, {save_card: save_card});
                                                                    IntegratedPayment.props.api.onCompleted(function (event) {
                                                                        window.location.replace('<?= $escaper->escapeUrl($block->getUrl('payplug_payments/payment/paymentReturn')); ?>');
                                                                        resolve();
                                                                    });

                                                                } else {
                                                                    window.location.replace('<?= $escaper->escapeUrl($block->getUrl('payplug_payments/payment/cancel')); ?>');
                                                                    reject();

                                                                }
                                                            }
                                                        });
                                                    });
                                                } else {
                                                    reject();
                                                    magewire.plugins.loader.stop();
                                                    document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
                                                    return false;
                                                }
                                            });
                                        });
                                    });
                                }
                            }
                        },
                        loadHostedLib() {
                            return new Promise((resolve, reject) => {
                                if (!document.getElementById('payplug_hosted_lib')) {
                                    const script = document.createElement('script');
                                    script.src = 'https://cdn-qa.payplug.com/js/integrated-payment/v1@1/index.js';
                                    script.setAttribute('id', 'payplug_hosted_lib');
                                    document.head.append(script);
                                }
                                //if it's not loaded yet let's wait 100ms to load it
                                let count = 0;
                                const interval = setInterval(() => {
                                    count++;
                                    if (typeof Payplug !== 'undefined') {
                                        clearInterval(interval);
                                        resolve();
                                        return;
                                    }
                                    if (count > 100) {
                                        reject();
                                        clearInterval(interval);
                                        throw new Error('Unable to load Payplug');
                                    }
                                }, 100);
                            });
                        },
                        checkLoaded: function () {
                            return document.body.contains(document.getElementById('cardholder'));
                        },
                    }, document.getElementById('payplug-payment-form'), 'payment');

                    if (document.querySelector('ul.payplug-payments-cards li') != null) {
                        document.querySelector('ul.payplug-payments-cards li input').click()
                        document.querySelector('ul.payplug-payments-cards').addEventListener('change', function () {
                            var card = document.querySelector('input[name="payment[payplug_payments_standard][customer_card_id]"]:checked');
                            if (card.value === '') {
                                oneclick = false;
                                if (integrated) {
                                    document.querySelector("#payplug-payment-form").classList.remove("-hide");
                                }
                            } else {
                                oneclick = true;
                                if (integrated) {
                                    document.querySelector("#payplug-payment-form").classList.add("-hide");
                                }
                            }
                        });
                    }
                } else {
                    var script = document.getElementById("payplug-js");
                    if (script) {
                        script.remove();
                    }
                    document.querySelector('.btn-primary[x-bind="buttonPlaceOrder()"]').disabled = false;
                    hyvaCheckout.payment.method = null;
                }
            }, {once: true});

            if (integrated) {
                const cardholder = document.querySelector('#cardholder-input-container');
                const pan = document.querySelector('#pan-input-container');
                const exp = document.querySelector('#exp-input-container');
                const cvv = document.querySelector('#cvv-input-container');
                const options = { attributes: true }
                function callback(mutationList, observer) {
                    mutationList.forEach(function(mutation) {
                        if ( mutation.attributeName === 'class' ) {
                            if (mutation.target.classList.contains("integrated_payment_error")) {
                                mutation.target.style.border = "1px solid #FF0000";
                                let id = mutation.target.id
                                document.querySelector('.error-container.'+id+ ' .invalid-field').style.display = "block";
                            } else {
                                let id = mutation.target.id
                                mutation.target.style.border = "1px solid #d5d6d8";
                                document.querySelector('.error-container.'+id+ ' .invalid-field').style.display = "none";
                            }
                        }
                    })
                }
                const observer = new MutationObserver(callback)
                observer.observe(cardholder, options)
                observer.observe(pan, options)
                observer.observe(exp, options)
                observer.observe(cvv, options)
            }
        })();
    </script>
</div>
